language: node_js
node_js:
  - "7"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE datastudio;'
  - echo "DS_DB_HOST=localhost" >> /etc/environment
  - echo "DS_DB_USER=travis" >> /etc/environment
  - echo "DS_DB_PASS=" >> /etc/environment
  - echo "DS_DB_NAME=datastudio" >> /etc/environment
  - echo "DS_SERVER_NAME=api.datastudio.localhost" >> /etc/environment
  - echo "DS_SERVER_PROTOCOL=http" >> /etc/environment

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cat /vagrant/src/sql/*.sql | mysql -h localhost -u travis -p datastudio
  - cat /vagrant/src/sql/data/*.sql | mysql -h localhost -u travis -p datastudio

script:
  - npm test

git:
  depth: 10
